// Scans data
let scanData = {
    post_easter: {
        name: "Пасхальная открытка",
        date: "12 апреля 2020/ Санкт-Петербург",
        description: "Получил в Анненкирхе на пасху",
        src: "img/открытка-15.png",
        sound: "On",
    },
    peace: {
        name: "Карточка «Любовь и Мир»",
        date: "11 января 2018/ Москва",
        description: "",
        src: "img/билет.png",
        sound: "On",
    },
    icon1: {
        name: "Икона",
        date: "4 июля 2007/ Москва",
        src: "img/икона-42.png",
        description: "",
        sound: "On",
    },
    cap: {
        name: "Крыжечка",
        date: "20 октябрь 2021/ Москва",
        src: "img/крыжечка.png",
        description: "Оставил на память о лете 2021",
        sound: "On",
    },
    card1: {
        name: "Игральная карта",
        date: "20 января 1988/ Москва",
        src: "img/мал-карта-1.png",
        description: "Мамины карточки",
        sound: "On",
    },
    sketch1: {
        name: "Скетчбук",
        description: "С 2021 года каждый день со мной",
        date: "2 августа 2021/ Ярославль",
        src: "img/блокнок2.png",
        sound: "On",
    },
    sticker1: {
        name: "Наклейка",
        date: "12 декабря 2022/ Москва",
        src: "img/sticker2.png",
        description: "Из Скуратова",
        sound: "On",
    },
    sketch2: {
        name: "Блокнот",
        date: "10 марта 2018/ Санкт-Петербург",
        src: "img/notebook.png",
        description: "Память о поездке в Питер",
        sound: "On",
    },
    post_porte: {
        name: "Открытка “Porte A”",
        date: "18 февраля 2022/ Москва",
        src: "img/открытка-7.png",
        description: "",
        sound: "On",
    },
    book_shishkan: {
        name: "Книга Константина Шишкана",
        date: "12 сентября 1995/ Москва",
        src: "img/book-shish.png",
        description: "",
        sound: "On",
    },
    braclet1: {
        name: "Фенечка",
        date: "27 июля 2019/ Переславль-Залесский",
        src: "img/фенечка-2.png",
        description: "Подарила подруга в лагере",
        sound: "On",
    },
    post_girl: {
        name: "Рисунок Маши Б. для Саши П.",
        date: "6 мая 2022/ Москва",
        src: "img/открытка-4.png",
        description: "Подарок на день рождения",
        sound: "On",
    },
    money: {
        name: "Пять лари",
        date: "18 августа 2023/ Тбилиси",
        src: "img/деньги.png",
        description: "Сохранил, чтобы давать на чай в грузинских ресторанах :)",
        sound: "On",
    },
    cat: {
        name: "Фотография кота",
        date: "23 августа 2023/ Тбилиси",
        src: "img/кот-1-1.png",
        description: "",
        sound: "On",
    },
    post_africa: {
        name: "Открытка Гоген",
        date: "18 апреля 2019/ Санкт-Петербург",
        src: "img/открытка_африка.png",
        description: "",
        sound: "On",
    },
    polaroid: {
        name: "Застолье Сережи К.",
        date: "9 июня 1992/ Москва",
        src: "img/фото.png",
        description: "Фотография от дяди",
        sound: "On",
    },
    basquiat: {
        name: "Зин про Баскиата",
        date: "26 декабря 2022/ Москва",
        src: "img/баския.png",
        description: "Зин-переосмысление Баскии. Лицей 11 класс",
        sound: "On",
    },

    card2: {
        name: "Игральная карта",
        date: "20 января 1988/ Москва",
        src: "img/мал-карта-0.png",
        description: "Мамины карточки",
        sound: "On",
    },
    baby: {
        name: "Рисунок Риты С.",
        date: "18 октября 2019/ Москва",
        src: "img/бэбик.png",
        description: "",
        sound: "On",
    },
    vgik: {
        name: "Бэйджик фестиваля",
        date: "26 ноября 2022/ Москва",
        src: "img/вгик.png",
        description: "Подарок на память о фестивале от Саши Г. и Маши Е.",
        sound: "On",
    },
    georgia1: {
        name: "Закладка",
        date: "26 августа 2023/ Тбилиси",
        src: "img/закладка.png",
        description: "",
        sound: "On",
    },
    tree: {
        name: "Фотография деревьев",
        date: "3 мая 2020/ Ярославль",
        src: "img/дерево.png",
        description: "Главная фотография дистанционки",
        sound: "On",
    },
    tree: {
        name: "Фотография деревьев",
        date: "3 мая 2020/ Ярославль",
        src: "img/дерево.png",
        description: "",
        sound: "On",
    },
    ticket: {
        name: "Проездной Дениса П.",
        date: "10 июля 1989/ Москва",
        src: "img/билетик_старый.png",
        description: "Проездной папы",
        sound: "On",
    },
    braclet2: {
        name: "Браслетик",
        date: "21 июня 2016/ Испания",
        src: "img/браслетик.png",
        description: "Подарок от мамы",
        sound: "On",
    },
    icon2: {
        name: "Икона",
        date: "9 апреля 2013/ Москва",
        src: "img/икона-1.png",
        description: "",
        sound: "On",
    },
    post_cat: {
        name: "Открытка с котиком",
        date: "29 мая 2021/ Ярослалвь",
        src: "img/открытка-18.png",
        description: "",
        sound: "On",
    },
    sticker2: {
        name: "Наклейка",
        date: "12 декабря 2022/ Москва",
        src: "img/sticker.png",
        description: "",
        sound: "On",
    },
    scrap: {
        name: "Скрепка",
        date: "4 сентября 2021/ Москва",
        src: "img/скрепка.png",
        description: "",
        sound: "On",
    },
    sketch3: {
        name: "Черновик",
        date: "1 декабря 2023/ Москва",
        src: "img/блокнок.png",
        description: "Милое письмо, на день рождения",
        sound: "On",
    },
    tram: {
        name: "Трамвайный водитель",
        date: "7 мая 2022/ Ярославль",
        src: "img/IMG_4927.png",
        description: "Троюродный прапрадедушка из СПб",
        sound: "On",
    },
    card3: {
        name: "Игральная карта",
        date: "20 января 1988/ Москва",
        src: "img/мал-карта-6.png",
        description: "Мамины карточки",
        sound: "On",
    },
    moomin: {
        name: "Карточка Муми-тролли",
        date: "2 августа 2018/ Ростов-на-Дону",
        src: "img/карточка.png",
        description: "",
        sound: "On",
    },
    post_catstar: {
        name: "Открытка с котиками",
        date: "19 мая 2023/ Москва",
        src: "img/грибы.png",
        description: "Открытка от лагерных друзей на встречу спустя 4 года после последней смены",
        sound: "On",
    },
    nice1: {
        name: "Проездной в Ницце",
        date: "18 февраля 2020/ Ницца",
        src: "img/ницца2.png",
        description: "",
        sound: "On",
    },
    card4: {
        name: "Игральная карта",
        date: "20 января 1988/ Москва",
        src: "img/мал-карта-1.png",
        description: "Мамины карточки",
        sound: "On",
    },
    kino: {
        name: "Стих про кино",
        date: "15 сентября 2019/ Москва",
        src: "img/кинцо.png",
        description: "",
        sound: "On",
    },
    ipod: {
        name: "Плеер Ipod",
        date: "1 октября 2012/ Ярославль",
        src: "img/плеер.png",
        description: "",
        sound: "On",
    },
    tel_aviv: {
        name: "Белый город, черный город",
        date: "25 марта 2023/ Новосибирск",
        src: "img/tel-aviv.png",
        description: "",
        sound: "On",
    },
    post_sheep: {
        name: "Открытка с овечкой",
        date: "14 января 2021/ Москва",
        src: "img/открытка-8.png",
        description: "",
        sound: "On",
    },
    sochi: {
        name: "Подарочный блокнот Ульяне",
        date: "1 июня 2013/ Сочи",
        src: "img/блокнот.png",
        description: "Лучший подарок!",
        sound: "On",
    },
    msk_t1: {
        name: "Московский проездной",
        date: "10 августа 2021/ Москва",
        src: "img/ткарта-москва3.png",
        description: "",
        sound: "On",
    },
    envelope: {
        name: "Конверт",
        date: "24 декабря 1971/ Москва",
        src: "img/конверт.png",
        description: "Письмо бабушке",
        sound: "On",
    },
    ticket_air1: {
        name: "Посадочный",
        date: "1 августа 2021/ Стамбул",
        src: "img/ткарты.png",
        description: "Домой",
        sound: "On",
    },
    georgia2: {
        name: "Блокнот с алфавитом",
        date: "25 августа 2023/ Тбилиси",
        src: "img/грузия2.png",
        description: "",
        sound: "On",
    },
    matches: {
        name: "Спички",
        date: "17 декабря 2010/ Ярослалвь",
        src: "img/спички.png",
        description: "Их запах — воспоминания о бабушкиных блинах и горячем чае",
        sound: "On",
    },
    nice2: {
        name: "Фотография",
        date: "1 марта 2020/ Ницца",
        src: "img/ницца.png",
        description: "",
        sound: "On",
    },
    card5: {
        name: "Игральная карта",
        date: "20 января 1988/ Москва",
        src: "img/мал-карта-6.png",
        description: "Мамины картчоки",
        sound: "On",
    },
    msk_t2: {
        name: "Московский проездной",
        date: "26 июня 2021/ Москва",
        src: "img/ткарта-москва2.png",
        description: "",
        sound: "On",
    },
    post_mushrooms: {
        name: "Открытка с грибами",
        date: "19 мая 2023/ Москва",
        src: "img/грибы2.png",
        description: "Подарок с чудесный посланием на обороте",
        sound: "On",
    },
    ticket_air2: {
        name: "Посадочный",
        date: "30 декабря 2022/ Москва",
        src: "img/билетик-3.png",
        description: "На Новый год к Папе в Грузию",
        sound: "On",
    },
    istanbul: {
        name: "Проездной",
        date: "1 ноября 2022/ Стамбул",
        src: "img/стамбул.png",
        description: "",
        sound: "On",
    },
    paper_summer: {
        name: "Стихотворение про лето",
        date: "31 августа 2018/ Ростов-на-Дону",
        src: "img/бумажечка.png",
        description: "",
        sound: "On",
    },
    braclet3: {
        name: "Фенечка",
        date: "3 августа 2019/ Переславль-Залесский",
        src: "img/фенечка-1.png",
        description: "Фенечка-напоминание о лагере",
        sound: "On",
    },
    icon3: {
        name: "Икона",
        date: "6 мая 2004/ Москва",
        src: "img/икона-82.png",
        description: "",
        sound: "On",
    },
    book1: {
        name: "Карманный словарь",
        date: "2 сентября 1969/ Москва",
        src: "img/грузия.png",
        description: "",
        sound: "On",
    },
    post_green: {
        name: "Открытка ",
        date: "13 ноября 1998/ Москва",
        src: "img/открытка-6.png",
        description: "",
        sound: "On",
    },
}
export default scanData;